namespace Hex1b.Automation;

internal sealed record Hex1bTerminalSnapshotState(
    int TerminalWidth,
    int TerminalHeight,
    int CursorX,
    int CursorY,
    bool InAlternateScreen,
    bool CursorVisible,
    bool BracketedPasteEnabled,
    bool ApplicationCursorKeysEnabled,
    bool ApplicationKeypadEnabled,
    bool FocusEventsEnabled,
    bool MouseProtocolX10Enabled,
    bool MouseProtocolNormalEnabled,
    bool MouseProtocolHighlightEnabled,
    bool MouseProtocolButtonEnabled,
    bool MouseProtocolAnyEnabled,
    bool MouseEncodingUtf8Enabled,
    bool MouseEncodingSgrEnabled,
    bool MouseEncodingUrxvtEnabled,
    int CursorShape,
    DateTimeOffset Timestamp,
    int CellPixelWidth,
    int CellPixelHeight,
    TerminalCell[,] ScreenBuffer,
    ScrollbackRow[] ScrollbackRows,
    IReadOnlyList<KgpPlacement> KgpPlacements,
    IReadOnlyDictionary<uint, KgpImageData> KgpImages);
