// <auto-generated/>
//
// Baseline suppressions for HEX1B0001 (WidgetMethodNamePrefixedWithWith).
//
// This file enumerates every existing widget With* method in the lib so that the analyzer
// can ship as a project-wide Warning without breaking TreatWarningsAsErrors=true. New With*
// methods on widgets added after this file was generated will NOT be silently suppressed —
// they will fail the build, prompting either a rename or an explicit, justified addition here.
//
// To remove a suppression: rename the offending method (drop the "With" prefix) and delete
// the corresponding [SuppressMessage] line below. When this file is empty, delete it.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.InputBindingExtensions.WithInputBindings``1(``0,System.Action{Hex1b.Input.InputBindingsBuilder})")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.KgpImageExtensions.WithHeight(Hex1b.Widgets.KgpImageWidget,System.Int32)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.KgpImageExtensions.WithStretch(Hex1b.Widgets.KgpImageWidget,Hex1b.KgpImageStretch)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.KgpImageExtensions.WithWidth(Hex1b.Widgets.KgpImageWidget,System.Int32)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.QrCodeExtensions.WithQuietZone(Hex1b.Widgets.QrCodeWidget,System.Int32)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.TerminalExtensions.WithMouseWheelScrollAmount(Hex1b.Widgets.TerminalWidget,System.Int32)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.BackdropWidget.WithBackground(Hex1b.Theming.Hex1bColor)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.BackdropWidget.WithLayerId(System.String)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.DrawerWidget.WithMode(Hex1b.Widgets.DrawerMode)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.EditorWidget.WithViewRenderer(Hex1b.IEditorViewRenderer)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.FormTextFieldWidget.WithHeight(System.Int32)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.FormTextFieldWidget.WithInitialValue(System.String)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.FormTextFieldWidget.WithLabelPlacement(Hex1b.Widgets.LabelPlacement)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.FormTextFieldWidget.WithMaxWidth(System.Int32)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.FormTextFieldWidget.WithMinWidth(System.Int32)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.FormTextFieldWidget.WithValidateOn(Hex1b.Widgets.ValidateOn)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.FormTextFieldWidget.WithWidth(System.Int32)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.FormWidget.WithLabelPlacement(Hex1b.Widgets.LabelPlacement)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.FormWidget.WithLabelWidth(System.Int32)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.HyperlinkWidget.WithId(System.String)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.HyperlinkWidget.WithParameters(System.String)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.NotificationIconWidget.WithBell(System.String)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.NotificationIconWidget.WithCount(System.Boolean)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.NotificationPanelWidget.WithAnimation(System.Boolean)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.NotificationPanelWidget.WithContent(Hex1b.Widgets.Hex1bWidget)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.NotificationPanelWidget.WithDrawerFloats(System.Boolean)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.NotificationPanelWidget.WithMaxFloating(System.Int32)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.NotificationPanelWidget.WithOffset(System.Int32,System.Int32)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.PastableWidget.WithMaxSize(System.Int32)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.PastableWidget.WithTimeout(System.TimeSpan)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.RescueWidget.WithFallback(System.Func{Hex1b.RescueContext,Hex1b.Widgets.Hex1bWidget})")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.TabItemWidget.WithIcon(System.String)")]
[assembly: SuppressMessage("Hex1b.ApiDesign", "HEX1B0001:WidgetMethodNamePrefixedWithWith", Justification = "Pre-existing API; tracked for rename.", Scope = "member", Target = "~M:Hex1b.Widgets.TilePanelWidget.WithPointsOfInterest(System.Collections.Generic.IReadOnlyList{Hex1b.Data.TilePointOfInterest})")]
