using System.Text.Json.Serialization;

namespace Hex1b.LanguageServer.Protocol;

/// <summary>
/// Source-generated JSON context for LSP (Language Server Protocol) types.
/// Provides AOT-compatible serialization for all LSP message types.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
// JSON-RPC messages
[JsonSerializable(typeof(JsonRpcRequest))]
[JsonSerializable(typeof(JsonRpcNotification))]
[JsonSerializable(typeof(JsonRpcResponse))]
[JsonSerializable(typeof(JsonRpcError))]
[JsonSerializable(typeof(CancelParams))]
[JsonSerializable(typeof(JsonRpcServerResponse))]
// Basic types
[JsonSerializable(typeof(LspPosition))]
[JsonSerializable(typeof(LspRange))]
[JsonSerializable(typeof(TextDocumentIdentifier))]
[JsonSerializable(typeof(VersionedTextDocumentIdentifier))]
[JsonSerializable(typeof(TextDocumentItem))]
[JsonSerializable(typeof(WorkspaceFolder))]
// Initialize
[JsonSerializable(typeof(InitializeParams))]
[JsonSerializable(typeof(InitializeResult))]
[JsonSerializable(typeof(ClientCapabilities))]
[JsonSerializable(typeof(ServerCapabilities))]
[JsonSerializable(typeof(TextDocumentClientCapabilities))]
[JsonSerializable(typeof(WorkspaceClientCapabilities))]
[JsonSerializable(typeof(DynamicRegistrationCapability))]
[JsonSerializable(typeof(SynchronizationClientCapabilities))]
[JsonSerializable(typeof(HoverClientCapabilities))]
[JsonSerializable(typeof(SignatureHelpClientCapabilities))]
[JsonSerializable(typeof(SignatureInformationClientCapabilities))]
[JsonSerializable(typeof(ParameterInformationClientCapabilities))]
[JsonSerializable(typeof(DocumentSymbolClientCapabilities))]
[JsonSerializable(typeof(CodeActionClientCapabilities))]
[JsonSerializable(typeof(CodeActionLiteralSupportCapabilities))]
[JsonSerializable(typeof(CodeActionKindCapabilities))]
[JsonSerializable(typeof(RenameClientCapabilities))]
[JsonSerializable(typeof(FoldingRangeClientCapabilities))]
[JsonSerializable(typeof(CompletionClientCapabilities))]
[JsonSerializable(typeof(CompletionItemClientCapabilities))]
[JsonSerializable(typeof(CompletionItemResolveSupportCapabilities))]
[JsonSerializable(typeof(CompletionItemKindClientCapabilities))]
[JsonSerializable(typeof(SemanticTokensClientCapabilities))]
[JsonSerializable(typeof(SemanticTokensRequests))]
[JsonSerializable(typeof(PublishDiagnosticsClientCapabilities))]
// Server option types
[JsonSerializable(typeof(CompletionOptions))]
[JsonSerializable(typeof(SignatureHelpOptions))]
[JsonSerializable(typeof(CodeLensOptions))]
[JsonSerializable(typeof(DocumentLinkOptions))]
// Document sync
[JsonSerializable(typeof(DidOpenTextDocumentParams))]
[JsonSerializable(typeof(DidChangeTextDocumentParams))]
[JsonSerializable(typeof(TextDocumentContentChangeEvent))]
[JsonSerializable(typeof(DidCloseTextDocumentParams))]
[JsonSerializable(typeof(DidSaveTextDocumentParams))]
// Completion
[JsonSerializable(typeof(CompletionParams))]
[JsonSerializable(typeof(CompletionContext))]
[JsonSerializable(typeof(CompletionList))]
[JsonSerializable(typeof(CompletionItem))]
[JsonSerializable(typeof(CompletionItem[]))]
// Hover
[JsonSerializable(typeof(HoverParams))]
[JsonSerializable(typeof(HoverResult))]
[JsonSerializable(typeof(MarkupContent))]
// Navigation
[JsonSerializable(typeof(DefinitionParams))]
[JsonSerializable(typeof(Location))]
[JsonSerializable(typeof(Location[]))]
[JsonSerializable(typeof(LocationLink))]
[JsonSerializable(typeof(ReferenceParams))]
[JsonSerializable(typeof(ReferenceContext))]
[JsonSerializable(typeof(DocumentHighlightParams))]
[JsonSerializable(typeof(DocumentHighlight))]
[JsonSerializable(typeof(DocumentHighlight[]))]
// Editing
[JsonSerializable(typeof(TextEdit))]
[JsonSerializable(typeof(TextEdit[]))]
[JsonSerializable(typeof(RenameParams))]
[JsonSerializable(typeof(PrepareRenameParams))]
[JsonSerializable(typeof(PrepareRenameResult))]
[JsonSerializable(typeof(WorkspaceEdit))]
[JsonSerializable(typeof(TextDocumentEdit))]
[JsonSerializable(typeof(Command))]
[JsonSerializable(typeof(CodeActionParams))]
[JsonSerializable(typeof(CodeActionContext))]
[JsonSerializable(typeof(CodeAction))]
[JsonSerializable(typeof(CodeAction[]))]
[JsonSerializable(typeof(FormattingOptions))]
[JsonSerializable(typeof(DocumentFormattingParams))]
[JsonSerializable(typeof(DocumentRangeFormattingParams))]
// Signature help
[JsonSerializable(typeof(SignatureHelpParams))]
[JsonSerializable(typeof(SignatureHelpContext))]
[JsonSerializable(typeof(SignatureHelp))]
[JsonSerializable(typeof(SignatureInformation))]
[JsonSerializable(typeof(ParameterInformation))]
// Document structure
[JsonSerializable(typeof(DocumentSymbolParams))]
[JsonSerializable(typeof(DocumentSymbol))]
[JsonSerializable(typeof(DocumentSymbol[]))]
[JsonSerializable(typeof(FoldingRangeParams))]
[JsonSerializable(typeof(FoldingRange))]
[JsonSerializable(typeof(FoldingRange[]))]
[JsonSerializable(typeof(SelectionRangeParams))]
[JsonSerializable(typeof(SelectionRange))]
[JsonSerializable(typeof(SelectionRange[]))]
// Advanced
[JsonSerializable(typeof(InlayHintParams))]
[JsonSerializable(typeof(InlayHint))]
[JsonSerializable(typeof(InlayHint[]))]
[JsonSerializable(typeof(InlayHintLabelPart))]
[JsonSerializable(typeof(InlayHintLabelPart[]))]
[JsonSerializable(typeof(CodeLensParams))]
[JsonSerializable(typeof(CodeLens))]
[JsonSerializable(typeof(CodeLens[]))]
[JsonSerializable(typeof(DocumentLinkParams))]
[JsonSerializable(typeof(DocumentLink))]
[JsonSerializable(typeof(DocumentLink[]))]
// Call/Type hierarchy
[JsonSerializable(typeof(CallHierarchyPrepareParams))]
[JsonSerializable(typeof(CallHierarchyItem))]
[JsonSerializable(typeof(CallHierarchyItem[]))]
[JsonSerializable(typeof(CallHierarchyIncomingCallsParams))]
[JsonSerializable(typeof(CallHierarchyIncomingCall))]
[JsonSerializable(typeof(CallHierarchyIncomingCall[]))]
[JsonSerializable(typeof(CallHierarchyOutgoingCallsParams))]
[JsonSerializable(typeof(CallHierarchyOutgoingCall))]
[JsonSerializable(typeof(CallHierarchyOutgoingCall[]))]
[JsonSerializable(typeof(TypeHierarchyPrepareParams))]
[JsonSerializable(typeof(TypeHierarchyItem))]
[JsonSerializable(typeof(TypeHierarchyItem[]))]
[JsonSerializable(typeof(TypeHierarchySupertypesParams))]
[JsonSerializable(typeof(TypeHierarchySubtypesParams))]
// Semantic tokens
[JsonSerializable(typeof(SemanticTokensParams))]
[JsonSerializable(typeof(SemanticTokensResult))]
// Diagnostics & Progress
[JsonSerializable(typeof(PublishDiagnosticsParams))]
[JsonSerializable(typeof(LspDiagnostic))]
[JsonSerializable(typeof(WorkDoneProgress))]
[JsonSerializable(typeof(WorkDoneProgressValue))]
// Primitives
[JsonSerializable(typeof(string[]))]
internal sealed partial class LspJsonContext : JsonSerializerContext
{
}
