#!/usr/bin/env bash
# Regenerates the frozen Kitty Unicode-placeholder row/column diacritic table.
# Pass --check to verify that the committed generated source is current.

set -euo pipefail

MODE="${1:-generate}"
if [[ "$MODE" != "generate" && "$MODE" != "--check" ]]; then
  echo "usage: $0 [--check]" >&2
  exit 2
fi

SOURCE_URL="https://raw.githubusercontent.com/kovidgoyal/kitty/54416498c89e1d07e5079c49d15470dd0d947ce7/gen/rowcolumn-diacritics.txt"
SOURCE_SHA256="a80368b3272c41d8b50f3f640cf4305b6423e5a1aae6b72a405129bc29425f2c"
OUTPUT="src/Hex1b/Kgp/KgpUnicodePlaceholderDiacritics.Generated.cs"
SOURCE_FILE="$(mktemp)"
GENERATED_FILE="$(mktemp)"
trap 'rm -f "$SOURCE_FILE" "$GENERATED_FILE"' EXIT

curl -fsSL "$SOURCE_URL" -o "$SOURCE_FILE"

if command -v sha256sum >/dev/null 2>&1; then
  ACTUAL_SHA256="$(sha256sum "$SOURCE_FILE" | awk '{print $1}')"
else
  ACTUAL_SHA256="$(shasum -a 256 "$SOURCE_FILE" | awk '{print $1}')"
fi

if [[ "$ACTUAL_SHA256" != "$SOURCE_SHA256" ]]; then
  echo "unexpected source SHA-256: $ACTUAL_SHA256" >&2
  exit 1
fi

python3 - "$SOURCE_FILE" "$GENERATED_FILE" "$SOURCE_SHA256" <<'PY'
from pathlib import Path
import sys

source_path, output_path, source_sha = sys.argv[1:]
code_points = [
    int(line.split(";", 1)[0], 16)
    for line in Path(source_path).read_text(encoding="utf-8").splitlines()
    if line and not line.startswith("#")
]

lines = [
    "// <auto-generated>",
    "// Generated from kitty's rowcolumn-diacritics.txt at commit",
    "// 54416498c89e1d07e5079c49d15470dd0d947ce7.",
    f"// Source SHA-256: {source_sha}",
    "// The data is derived from UnicodeData.txt for Unicode 6.0.0.",
    "// </auto-generated>",
    "",
    "using System.Text;",
    "",
    "namespace Hex1b;",
    "",
    "internal static class KgpUnicodePlaceholderDiacritics",
    "{",
    "    internal const string SourceSha256 =",
    f'        "{source_sha}";',
    "",
    "    private static readonly int[] s_codePoints =",
    "    [",
]

for start in range(0, len(code_points), 8):
    values = ", ".join(f"0x{value:04X}" for value in code_points[start:start + 8])
    lines.append(f"        {values},")

lines.extend([
    "    ];",
    "",
    "    internal static ReadOnlySpan<int> CodePoints => s_codePoints;",
    "",
    "    internal static bool TryGetIndex(Rune value, out int index)",
    "    {",
    "        index = Array.BinarySearch(s_codePoints, value.Value);",
    "        return index >= 0;",
    "    }",
    "}",
    "",
])

Path(output_path).write_text("\n".join(lines), encoding="utf-8")
PY

if [[ "$MODE" == "--check" ]]; then
  if ! cmp -s "$GENERATED_FILE" "$OUTPUT"; then
    echo "$OUTPUT is not current; run $0" >&2
    diff -u "$OUTPUT" "$GENERATED_FILE" || true
    exit 1
  fi
  echo "$OUTPUT is current."
else
  mv "$GENERATED_FILE" "$OUTPUT"
  echo "Generated $OUTPUT."
fi
