namespace Hex1b.Terminal;

/// <summary>
/// Extended filter interface that allows transforming output based on terminal state.
/// </summary>
/// <remarks>
/// <para>
/// This interface extends <see cref="IHex1bTerminalPresentationFilter"/> to allow filters
/// to transform output data before it's sent to the presentation layer. Filters implementing
/// this interface can access the terminal's screen buffer to make optimization decisions.
/// </para>
/// <para>
/// The transformation happens after the terminal has processed the output into its screen buffer
/// but before the ANSI sequences are sent to the presentation adapter. This allows filters to:
/// <list type="bullet">
///   <item>Compare current and previous screen buffer states</item>
///   <item>Generate optimized ANSI sequences for only changed cells</item>
///   <item>Suppress redundant updates</item>
///   <item>Batch or transform output for efficiency</item>
/// </list>
/// </para>
/// </remarks>
public interface IHex1bTerminalPresentationTransformFilter : IHex1bTerminalPresentationFilter
{
    /// <summary>
    /// Transforms output before it's sent to the presentation layer.
    /// </summary>
    /// <param name="originalOutput">The original ANSI output generated by the terminal.</param>
    /// <param name="screenBuffer">Current state of the terminal screen buffer.</param>
    /// <param name="width">Terminal width in columns.</param>
    /// <param name="height">Terminal height in rows.</param>
    /// <param name="elapsed">Time elapsed since session start.</param>
    /// <returns>
    /// The transformed output to send to the presentation layer, or null/empty to suppress output entirely.
    /// </returns>
    ValueTask<ReadOnlyMemory<byte>> TransformOutputAsync(
        ReadOnlyMemory<byte> originalOutput,
        TerminalCell[,] screenBuffer,
        int width,
        int height,
        TimeSpan elapsed);
}
