name: 'Generate Version'
description: 'Generates version strings for NuGet packages'

outputs:
  preview:
    description: 'Preview version for GitHub Packages (0.1.0-preview.[run].[sha].[attempt])'
    value: ${{ steps.version.outputs.preview }}
  pr:
    description: 'PR version for GitHub Packages (0.1.0-[pr].[run].[sha].[attempt])'
    value: ${{ steps.version.outputs.pr }}
  release:
    description: 'Release version for NuGet.org (0.1.0)'
    value: ${{ steps.version.outputs.release }}

runs:
  using: 'composite'
  steps:
    - name: Generate versions
      id: version
      shell: bash
      run: |
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        PREVIEW_VERSION="0.1.0-preview.${{ github.run_id }}.${SHORT_SHA}.${{ github.run_attempt }}"
        PR_VERSION="0.1.0-pr.${{ github.event.pull_request.number }}.${{ github.run_id }}.${SHORT_SHA}.${{ github.run_attempt }}"
        
        RELEASE_VERSION="0.1.0"
        echo "preview=$PREVIEW_VERSION" >> $GITHUB_OUTPUT
        echo "pr=$PR_VERSION" >> $GITHUB_OUTPUT
        echo "release=$RELEASE_VERSION" >> $GITHUB_OUTPUT
        echo "Generated preview version: $PREVIEW_VERSION"
        echo "Generated PR version: $PR_VERSION"
        echo "Generated release version: $RELEASE_VERSION"
